name: 問題の報告
description: NoNICK.jsで発生しているバグや問題の報告を作成します。
labels: 'bug'
assignees: 
  - nonick-mc
body:
  - type: input
    id: feature
    attributes: 
      label: 問題が発生している機能
      description: 問題が発生している機能の名前や、Webページのリンクを入力してください。
    validations:
      required: true
  - type: textarea
    attributes: 
      label: どのような問題が発生していますか？
      description: 発生している問題について、**できる限り詳細に記入してください。** 必要に応じてスクリーンショットを追加することもできます。
    validations:
      required: true
  - type: dropdown
    id: products
    attributes:
      label: 問題が発生しているプロダクト
      description: 問題に関係するプロダクトを**1つ以上**選択してください。
      options:
        - Bot
        - Webダッシュボード
        - ドキュメント
      multiple: true
    validations:
      required: true
  
